Add section about bitshift operators
zeek/zeek-docs pull request #127
Opened 2022-07-17 03:48 UTC by AmazingPP

Doc for [Add bitshift operators](https://github.com/zeek/zeek/pull/2277)

2022-07-21 20:25 UTC, timwoj commented
I'm holding on merging this one until the questions in https://github.com/zeek/zeek/pull/2294 get resolved, mostly around whether we should support vector operations for this.

2022-07-21 20:27 UTC, timwoj requested changes

2022-07-21 20:27 UTC, timwoj commented on script-reference/operators.rst
> +but the bitwise complement operator works with :zeek:type:`count` only.
```suggestion
of count``. The bitwise shift operators can also work with :zeek:type:`int`.
The bitwise complement operator works with :zeek:type:`count` only.
```

2022-07-21 20:27 UTC, timwoj commented on script-reference/types.rst
> +bitwise operations (``<<``, ``>>``).
```suggestion
bitwise shift operations (``<<``, ``>>``).
```

2022-07-21 20:27 UTC, timwoj commented on script-reference/types.rst
> +decrement each element in the vector. It also support the bitwise right shift (``<<``)
```suggestion
decrement each element in the vector. They also support the bitwise right shift (``<<``) 
```

2022-07-21 20:37 UTC, vpax commented
> whether we should support vector operations for this

Seems we shouldn't, as we're moving away from mixed scalar-and-vector operations (and it's very hard for me to picture wanting to support bit shifts with both operands being vectors!).

2022-08-03 16:58 UTC, timwoj commented on script-reference/types.rst
> +decrement each element in the vector. It also support the bitwise right shift (``<<``)
Now that https://github.com/zeek/zeek/pull/2309 was merged. This section can be removed since bit-shifting vectors returns a deprecation warning.

2022-08-04 17:39 UTC, timwoj approved these changes

2022-08-04 19:21 UTC, merged