Spelling
zeek/zeek-docs pull request #160
Opened 2022-11-18 03:04 UTC by jsoref

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/zeek-docs/commit/26928405db292c1eaa97baa23eab980b7463ec48#commitcomment-90296894

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/zeek-docs/commit/8ba614526b7a31cc35add69148d51073dec102c3

Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

2022-11-18 03:05 UTC, jsoref reviewed
Some corrections suggested by Google Sheets.

2022-11-18 03:05 UTC, jsoref commented on README
> +than here, so see the next section for how Zeekygen docs can be (re)generated.
This is by far the most interesting/worrisome change

2022-11-18 03:05 UTC, jsoref commented on cluster-setup.rst
> +See the project's `GitHub repository <https://github.com/luigirizzo/netmap>`_
brand

2022-11-18 17:07 UTC, timwoj requested changes

2022-11-18 18:43 UTC, ckreibich commented on logs/smb.rst
> +                  .... .... .... .... ...0 .... .... .... = Thirteenth: Thirteenth is NOT SET
Agreed.

2022-11-18 20:57 UTC, jsoref commented on logs/smb.rst
> +                  .... .... .... .... ...0 .... .... .... = Thirteenth: Thirteenth is NOT SET
Ah. Indeed, https://github.com/wireshark/wireshark/blob/f3a96bc18cfc1b0b434682fccc313c477d2ca86e/epan/dissectors/packet-dcerpc-atsvc.c#L161
Ok, added to my shopping list.

2022-12-12 23:46 UTC, ckreibich approved these changes
Thanks!

2022-12-13 00:05 UTC, merged