Add a section about JavaScript
zeek/zeek-docs pull request #192
Opened 2023-05-25 14:25 UTC by awelzel

2023-05-26 19:13 UTC, awelzel commented
Read the docs branch:

https://docs.zeek.org/en/topic-awelzel-js-docs/scripting/javascript.html

2023-05-26 19:18 UTC, timwoj requested changes

2023-05-26 19:18 UTC, timwoj commented on scripting/javascript.rst
> +   :caption: hello.js
```suggestion
   :caption: intel-insert.js
```

2023-05-26 19:18 UTC, timwoj commented on scripting/javascript.rst
> +In below example, the ``intel_item`` JavaScript object will be converted to
```suggestion
In the example below, the ``intel_item`` JavaScript object will be converted to
```

2023-05-27 14:56 UTC, awelzel commented on scripting/javascript.rst
> +builtin and third-party directly within Zeek.
> packages

That had said libraries at some point, so used that again. Thanks!

2023-05-27 15:04 UTC, awelzel commented on scripting/javascript.rst
> +The external `ZeekJS`_ plugin is included with Zeek as an optional builtin plugin.
I think @sethhall originally termed them "builtin plugins". I've been using builtin - when mentioning bifs, I'll try to adapt to built-in.

2023-05-31 08:29 UTC, timwoj approved these changes

2023-05-31 08:30 UTC, merged